### ISSUE TITLE
[Feature Request] 图标显示，图片放大

### ISSUE THREAD

**Issue by Swimcat** [ALPGO-AI/ui-admin#24]
# Feature Request

## 描述 Description

在图标显示中，可以让图片点击到就放大

## 使用案例 Use Case

在鼠标点击图片的时候，图片会放大

## 提议解决方案 Proposed Solution

为更方便的查看模型图片，图标显示中的图片，点击会放大

## 考虑的替代方案 Alternatives Considered

略

## 其他信息 Additional Information

略

**Comment by AsahiLuna** [comment]
resolved
