### ISSUE TITLE
[Feature Request] 图标显示中，点击图片显示详情

### ISSUE THREAD

**Issue by Swimcat** [ALPGO-AI/ui-admin#25]
# Feature Request

## 描述 Description

在模型的图标显示中，点击图片能显示图片详情

## 使用案例 Use Case

将解决图标显示中，图片点击无响应，让使用者更好的分辨信息

## 提议解决方案 Proposed Solution

点击图片后，显示图片详细信息

## 考虑的替代方案 Alternatives Considered

略
## 其他信息 Additional Information

略

**Comment by AsahiLuna** [comment]
resolved
